//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLaboratuvar
    {
        public int LaboratuvarID { get; set; }
        public Nullable<int> Doktor { get; set; }
        public Nullable<int> Hasta { get; set; }
        public string Talep { get; set; }
        public string Sonuc { get; set; }
    
        public virtual TblDoktor TblDoktor { get; set; }
        public virtual TblHasta TblHasta { get; set; }
    }
}
