//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMuayene
    {
        public int MuayeneID { get; set; }
        public Nullable<int> Doktor { get; set; }
        public Nullable<int> Hasta { get; set; }
        public Nullable<int> Bolum { get; set; }
        public string Oyku { get; set; }
        public string Teshis { get; set; }
        public string Tedavi { get; set; }
        public string Ilaclar { get; set; }
    
        public virtual TblBolum TblBolum { get; set; }
        public virtual TblDoktor TblDoktor { get; set; }
        public virtual TblHasta TblHasta { get; set; }
    }
}
